require 'rake'
require 'fileutils'

MRUBY_CONFIG_PATH = File.expand_path(ENV["MRUBY_CONFIG"] || "build_config.rb")

file :mruby do
  unless File.directory?('mruby')
    sh "git clone --depth=1 https://github.com/mruby/mruby.git"
  end
end

desc "compile binary"
task :compile => :mruby do
  Dir.chdir("mruby") do
    ENV["MRUBY_CONFIG"] = MRUBY_CONFIG_PATH
    sh "rake all"
  end
end

desc "test"
task :test => :mruby do
  Dir.chdir("mruby") do
    ENV["MRUBY_CONFIG"] = MRUBY_CONFIG_PATH
    sh "rake all test"
  end
end

desc "cleanup"
task :clean do
  Dir.chdir("mruby") do
    ENV["MRUBY_CONFIG"] = MRUBY_CONFIG_PATH
    sh "rake deep_clean"
  end
end

desc "minimize corpus ??? deduplicates and keeps only coverage-contributing inputs"
task :corpus_merge => :compile do
  fuzzer   = File.expand_path("mruby/build/host/bin/mruby-cbor-fuzzer")
  corpus   = File.expand_path("corpus")
  findings = File.expand_path("findings")
  merged   = File.expand_path("corpus_min")

  FileUtils.mkdir_p(merged)
  FileUtils.mkdir_p(corpus)

  dirs = [corpus]
  dirs << findings if File.directory?(findings)

  sh fuzzer, "-rss_limit_mb=5000", "-merge=1", merged, *dirs

  removed = Dir[File.join(corpus, "*")].count
  kept    = Dir[File.join(merged, "*")].count

  FileUtils.rm_rf(corpus)
  FileUtils.mv(merged, corpus)

  puts "Corpus minimized: #{removed} -> #{kept} inputs"
end

task :default => :test
